package parser;
/* Generated By:JavaCC: Do not edit this line. GambiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GambiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONFIG = 6;
  /** RegularExpression Id. */
  int SIMPLETEST = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int MULTIPLETEST = 10;
  /** RegularExpression Id. */
  int PROCEDURE = 11;
  /** RegularExpression Id. */
  int WEB = 12;
  /** RegularExpression Id. */
  int MOBILE = 13;
  /** RegularExpression Id. */
  int TARGET = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int APAREN = 17;
  /** RegularExpression Id. */
  int FPAREN = 18;
  /** RegularExpression Id. */
  int ACHAVE = 19;
  /** RegularExpression Id. */
  int FCHAVE = 20;
  /** RegularExpression Id. */
  int ACOUCHE = 21;
  /** RegularExpression Id. */
  int FCOUCHE = 22;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 23;
  /** RegularExpression Id. */
  int VIRGULA = 24;
  /** RegularExpression Id. */
  int PONTO = 25;
  /** RegularExpression Id. */
  int ATRIBUICAO = 26;
  /** RegularExpression Id. */
  int MAIORQUE = 27;
  /** RegularExpression Id. */
  int MENORQUE = 28;
  /** RegularExpression Id. */
  int NEG = 29;
  /** RegularExpression Id. */
  int MAIS = 30;
  /** RegularExpression Id. */
  int MENOS = 31;
  /** RegularExpression Id. */
  int ESTRELA = 32;
  /** RegularExpression Id. */
  int BARRA = 33;
  /** RegularExpression Id. */
  int MODULO = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int SQUOTE = 38;
  /** RegularExpression Id. */
  int DQUOTE = 39;
  /** RegularExpression Id. */
  int PROCALL = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"config\"",
    "\"simple\"",
    "\"begin\"",
    "\"end\"",
    "\"multiple\"",
    "\"proc\"",
    "\"@web\"",
    "\"@mobile\"",
    "<TARGET>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"|\"",
    "\"~\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<PROCALL>",
  };

}
