/* Generated By:JavaCC: Do not edit this line. LexicalAnalyzerConstants.java */
package lexicalAnalyzer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicalAnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIMPLETEST = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int MULTIPLETEST = 9;
  /** RegularExpression Id. */
  int PROCEDURE = 10;
  /** RegularExpression Id. */
  int WEB = 11;
  /** RegularExpression Id. */
  int MOBILE = 12;
  /** RegularExpression Id. */
  int CLICKBUTTON = 13;
  /** RegularExpression Id. */
  int ASSERTLABEL = 14;
  /** RegularExpression Id. */
  int BEFOREALL = 15;
  /** RegularExpression Id. */
  int AFTERALL = 16;
  /** RegularExpression Id. */
  int HEADER = 17;
  /** RegularExpression Id. */
  int GLOBAL = 18;
  /** RegularExpression Id. */
  int TARGET = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int APAREN = 22;
  /** RegularExpression Id. */
  int FPAREN = 23;
  /** RegularExpression Id. */
  int ACHAVE = 24;
  /** RegularExpression Id. */
  int FCHAVE = 25;
  /** RegularExpression Id. */
  int ACOUCHE = 26;
  /** RegularExpression Id. */
  int FCOUCHE = 27;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 28;
  /** RegularExpression Id. */
  int VIRGULA = 29;
  /** RegularExpression Id. */
  int PONTO = 30;
  /** RegularExpression Id. */
  int ATRIBUICAO = 31;
  /** RegularExpression Id. */
  int MAIORQUE = 32;
  /** RegularExpression Id. */
  int MENORQUE = 33;
  /** RegularExpression Id. */
  int NEG = 34;
  /** RegularExpression Id. */
  int MAIS = 35;
  /** RegularExpression Id. */
  int MENOS = 36;
  /** RegularExpression Id. */
  int ESTRELA = 37;
  /** RegularExpression Id. */
  int BARRA = 38;
  /** RegularExpression Id. */
  int MODULO = 39;
  /** RegularExpression Id. */
  int AND = 40;
  /** RegularExpression Id. */
  int OR = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int SQUOTE = 43;
  /** RegularExpression Id. */
  int DQUOTE = 44;
  /** RegularExpression Id. */
  int PROCALL = 45;
  /** RegularExpression Id. */
  int PARAM = 46;
  /** RegularExpression Id. */
  int IDENT = 47;
  /** RegularExpression Id. */
  int ARG = 48;
  /** RegularExpression Id. */
  int EMPTYPARAM = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"simple\"",
    "\"begin\"",
    "\"end\"",
    "\"multiple\"",
    "\"proc\"",
    "\"@web\"",
    "\"@mobile\"",
    "\"@clickButton\"",
    "\"@assertLabel\"",
    "\"beforeAll\"",
    "\"afterAll\"",
    "\"header\"",
    "\"global\"",
    "<TARGET>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"|\"",
    "\"~\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<PROCALL>",
    "<PARAM>",
    "<IDENT>",
    "<ARG>",
    "<EMPTYPARAM>",
  };

}
